// actions/types.ts
export const FETCH_GRAPHQL_DATA = "FETCH_GRAPHQL_DATA";
export const FETCH_GRAPHQL_DATA_SUCCESS = "FETCH_GRAPHQL_DATA_SUCCESS";
export const FETCH_GRAPHQL_DATA_ERROR = "FETCH_GRAPHQL_DATA_ERROR";
